version: '3'
services:
        db:
          image: postgres
          volumes:
            - ./postgresql-data:/var/lib/postgresql/data
          environment:
            - "POSTGRES_USER=akidai"
            - "POSTGRES_PASSWORD=Chemistry19931231"
            - "POSTGRES_HOST=vindex-master.cf4gj4qum9qn.ap-northeast-1.rds.amazonaws.com"

        app:
           build:
                context: .
                dockerfile: Dockerfile
           environment:
                RAILS_ENV: development
           ports:
             - '3000:3000'
           volumes:
             - .:/workdir
           tty: true
           stdin_open: true
           links: 
            - db